[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@2.3.6
    adafruit/Adafruit PWM Servo Driver Library@3.0.2
    adafruit/Adafruit BusIO@1.17.4
build_flags =
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
